### ISSUE TITLE
Add information that this is an ES6 module

### ISSUE THREAD

**Issue by vorg** [TatumCreative/geo-3d-box#1]

**Comment by gregtatum** [comment]
I can do this next time I'm at my dev computer. Any particular reason why the whole browserify transform would be noticeable by the end consumer? It gets transformed to ES5 code (except when used as a node.js type of application.)

**Comment by vorg** [comment]
Yes, I'm trying to use it in node.js type of application ([Plask](http://plask.org) / [pex](http://vorg.github.io/pex) to be precise).

I think it would be a good convention to mention ES6 just like glsl-\* modules mention they are designed for glslify.

**Comment by gregtatum** [comment]
Would it be helpful to also have something like this?

var genBox = require('geo-3d-box/es5')

I could output a transpiled version there.

**Comment by vorg** [comment]
Hmm, that could work but I don't want to pollute your repo and add another work in the future. I think the best way would be to simply add message in the README and then hopefully this will go away once node.js / io.js implements arrow functions and the other stuff. Thanks!

**Comment by gregtatum** [comment]
Resolved with 3a28b37e915ca4cfca225f1f9a51f02107432fc5
